### ISSUE TITLE
How to mount/automount a USB drive containing music so that snap can use it as ?

### ISSUE THREAD

**Issue by rmoorewrs** [arubislander/subsonic-snap#3]
I see from `snaps interfaces` that there's a subsonic-arubislander:removable-media plug, but I'm at a loss for how to connect a USB drive to that manually, let alone automatically (which would be nice).

Sorry, I'm new to snaps and my standard linux attempts to mount the usb drive and tell subsonic to use it as a media folder didn't seem to work. (the mount worked of course, but I don't think the subsonic-snap could see it). I'm OK with RTFM if I can get a pointer on where to read. Thanks

**Comment by arubislander** [comment]
Hi,

Thank you for reaching out :)

I need to add a proper description in the snap store so it is more discoverable maybe. If you do:
```
$ sudo snap connect subsonic-arubislander:removable-media
```
the snap should have access to your mounted USB drive. You only need to do the above once after installing. The connection should survive reboots and updates of the snap.

**Comment by rmoorewrs** [comment]
Thank you very much for the quick response! 

Yes, after running that `snap connect` command and manually mounting the USB drive to, say  `/media/usb-music` I can add a media folder in the web ui, pointing to `/media/usb-music` -- scans and plays perfectly. Thanks!

Is there some method in your snap to automount a USB device? Or is that something that needs to be done via systemd, or maybe some other snap?

Also, it doesn't seem like subsonic is aware of available storage devices on its own, which is too bad. On a raspberry pi zero w it almost makes a complete media player without any extra help.

**Comment by arubislander** [comment]
I am not sure I understand the question. Do you want to plug in a new media device and have it automatically mounted or do you want to have the mounted device be automatically added to subsonic's configuration, or both ?

The auto mounting is something that will need to be handled by the OS. There should be how-to's and tutorials online that provide instructions on getting that set up, although I am surprised it is not setup that way out of the box already. What distribution of Linux do you have running on your R Pi zero w?

The auto detection of a mounted device by subsonic is not a feature that the software itself provides. I suppose something could be attempted by using event hooks and clever scripting, but I would have to think long and hard on how to even begin such an attempt with the technology on hand.

Maybe you could elaborate some more on the precise work flow you are after in your particular use-case. Who knows, there might be a different solution altogether that is less of a challenge technically.

**Comment by rmoorewrs** [comment]
Good point, and sorry for being vague. 

Here's the story: A friend runs an office with speakers in the ceiling and wants to play their own nice music instead of FM Radio. Many possible options, so for the moment let's pretend old smart phones and cheap tablets aren't abundant. I'd like to build a simple media player/server with a spare Raspberry Pi Zero W, and your subsonic snap on Ubuntu core almost fits the bill perfectly.

So the #1  ideal flow would be: 
- user inserts a properly formatted USB drive containing their mp3s into the player/server
- USB drive is automatically mounted, scanned and added as a media folder to subsonic
- user logs in and all the new content from USB drive is available to play

If that's too difficult, the next best thing would be:
- user inserts a properly formatted USB drive containing their mp3s into the player/server
- USB drive is automatically mounted at a fixed/predictable mount point
- user logs in, adds the media folder and starts a scan 
- if the USB mount point is persistent (through USB removal/insertion) maybe only the scan is required 
  
Other thoughts:
- Mainly I'm trying to avoid requiring them to ssh into the player to mount/unmount the drive. 
- I'm ignoring the problem of finding/fixing the IP address for a headless device. In a one-off situation, I can set it manually for them. 
- I'm OK with limiting to only 1 USB drive at a time.

**Comment by arubislander** [comment]
That sounds like a sweet project! And your exploring the use of this snap in helping your friend is cool too.

I have a few additional questions: Would it be the same USB drive being disconnected and connected, or would it be a different one regularly? Did you consider using an external hard disk instead, with enough space to contain all of the audio?

Getting the USB drive to auto-mount should be possible with the correct systemd scripts. I am afraid I am not very knowledgeable in that area. And I am hesitant to recommend any of the solutions I came across online because I am not sure of their applicability to Ubuntu Core. Moreover, they seem to be concerned with mounting the external storage at boot time, and not 'hot swappable' as seems to be your intended use-case.

The same script that auto-mounts the USB drive could then trigger a scan on Subsonic via the rest API. You would need to pass along a username / password or username / salted and hashed password/salt combination on the url. (see [here](http://www.subsonic.org/pages/api.jsp#startScan) for more info on that.) I would suggest creating a dedicated user in Subsonic for this functionality.

This is some neat functionality to incorporate into the snap itself at some future time, offering added value for the user and added challenge for me to implement.

**Comment by rmoorewrs** [comment]
Thanks for the feedback, it's easier to learn something by doing a real project (for me at least) and I appreciate the conversation. So...

Ideally, it would be nice to plug in any random USB drive (or simultaneous drives) and have it/them mounted automatically. 

Depending on how difficult that proves to be on Ubuntu core, I can think of a few ways to dial back the complexity in a way that doesn't require a highly technical end user:
1. Limit to only one USB storage device at a time (but not require a specific device)
- make a single mount point with a fixed name
- persistent media folder is always pointed at that mount point

2. For multiple, simultaneous storage devices, use the drive's label as a mount point name?
- require unique label names
- can you create a media folder through the rest API?

3. Worst case, require power cycle/reboot after inserting USB drive to mount at boot time.

Triggering the rescan through the rest API is a great idea, sounds like it might be feasible to do at least some version of what I want (possibly with limitations above).

I'm not 100% certain I'll follow this through to the end (too many projects!), but I'll let you know if I come up with anything interesting (I'd be more than happy to contribute if that's appropriate). 

Thanks again, I didn't expect this much interaction. It's been a pleasant surprise and I'm learning a lot.

Rich

**Comment by arubislander** [comment]
Hi Rich,

I have enjoyed the interaction too. I would also be interested in hearing how you get on with the project. So feel free to keep me updated.

And of course contributions are welcomed!

Greetings,
Terence

**Comment by rmoorewrs** [comment]
So I made a little progress -- there's a snap called [udisks2](https://uappexplorer.com/snap/ubuntu/udisks2) that can be easily configured to automount media. The udisks2 snap [docs are here](https://docs.ubuntu.com/core/en/stacks/disk/udisks2/docs/installation).  

The snap can be installed and configured for automount like this:
```
snap install udisks2
snap set udisks2 automount.enable=true
```

After enabling automount, when a USB drive with a label like `music` is inserted, it automatically mounts the drive at `/media/root/music`. 

If there's a media folder defined in subsonic that points to `/media/root/music` already, all that's needed is to manually trigger a scan through the web  UI (and possibly a database cleanup).

This is close to being usable in a limited workflow as is, but there may be a few quirks to iron out:
- initially had trouble getting the SS media scan to recognize albums on the automounted USB drive
   - not sure if this is due to a permissions issue or
   - the fact that the SS media scan doesn't seem to like to go deeper than one level of hierarchy to find albums
   - I changed permissions before realizing the hierarchy problem, so maybe there's no issue at all... more testing needed

On how to automate, I can think of 2 options:
1. This would be a total hack, but `sudo udisksctl  monitor` prints out status messages as to when drives are inserted/removed. I could see watching that for the insertion message and triggering the rest API calls to subsonic...
2. It seems that udisks has a DBUS API (  [docs here](http://storaged.org/doc/udisks2-api/latest/ref-dbus.html]) ). I've never worked with DBUS, but maybe there's a way to listen for insertion/removal events? IDK

**Comment by arubislander** [comment]
Thank you for the update!

Yes, Subsonic does not like deep hierarchies for it's media folder. It seems to be happiest when the folder it is pointed to to be at most 2 subfolders deep e.g.: ./artist/album/song.mp3

There shouldn't be any permission issues, as everything under /media should be readable to a snap with the removable-media plug connected (well, almost everything, but definitely the contents in this case)

I have also never used the DBUS api, but you do raise a lot of interesting options and possibilities.
