### ISSUE TITLE
Transcode error with May 9 2020 Update

### ISSUE THREAD

**Issue by desroches25** [arubislander/subsonic-snap#4]
Hi There,

The latest update seems to have broken the transcode functionality on my instance. I've been using the Stable releases. 

Log error message: 
InputStreamReaderThread | (/root/snap/subsonic-arubislander/common/var/subsonic/transcode/ffmpeg) /root/snap/subsonic-arubislander/common/var/subsonic/transcode/ffmpeg: error while loading shared libraries: libslang.so.2: cannot open shared object file: No such file or directory
-- | --

I've checked and confirmed that I have libslang.so.2 and libslang.so.2.3.1:
libslang.so.2 -> libslang.so.2.3.1

Thanks
D

**Comment by arubislander** [comment]
Thank you for reaching out to me.

I will try to rectify this issue swiftly

**Comment by arubislander** [comment]
Hello again,

I reverted the version on the Release channel and also published a new version to the Candidate channel. Could you try switching to the candidate channel and see if the issue you reported is fixed? You can do this by going to the command line and typing:
```
sudo snap refresh subsonic-arubislander --candidate
```
Please let me know the results.

**Comment by desroches25** [comment]
Thanks for the quick support on this. Subsonic seems to have pulled a more recent version overnight. Once I started it this morning I can see it resolved to a different version - transcoding is working already without changing to candidate. I'll test refreshing to the candidate version and report back as well. 

Here is a dump from the log before changing to candidate:

[5/12/20 7:26:36 AM UTC] | INFO | VersionService | Resolved local Subsonic version to: 6.1.6
-- | -- | -- | --
[5/12/20 7:26:37 AM UTC] | INFO | MediaScannerService | Automatic media library scanning scheduled to run every 1 day(s), starting at Wed May 13 03:00:00 UTC 2020
[5/12/20 7:26:37 AM UTC] | INFO | UPnPService | Starting UPnP service...
[5/12/20 7:26:37 AM UTC] | INFO | PodcastService | Automatic Podcast update scheduled to run every 24 hour(s), starting at Tue May 12 07:31:37 UTC 2020
[5/12/20 7:26:37 AM UTC] | INFO | UPnPService | Disabling UPnP/DLNA media server
[5/12/20 7:26:37 AM UTC] | INFO | UPnPService | Starting UPnP service - Done!
[5/12/20 7:26:47 AM UTC] | WARN | NetworkService | No UPnP router found.
[5/12/20 7:31:37 AM UTC] | INFO | PodcastService | Starting scheduled Podcast refresh.
[5/12/20 7:31:37 AM UTC] | INFO | PodcastService | Completed scheduled Podcast refresh.
[5/12/20 7:48:48 AM UTC] | INFO | BootstrapVerificationFilter | Servlet container: jetty-6.1.x
[5/12/20 1:08:51 PM UTC] | INFO | VersionService | Resolved latest Subsonic final version to: 6.1.6
[5/12/20 1:08:51 PM UTC] | INFO | VersionService | Resolved latest Subsonic beta version to: 6.1.beta2

**Comment by desroches25** [comment]
The log indicates the same version as above after changing to latest candidate version.

I've pulled the beta version back down (May 9 update) and can confirm that it breaks the transcoding, so will run candidate for the time being. Let me know if you need further testing - unfortunately we're in opposite time zones.

**Comment by arubislander** [comment]
Thank you for getting back to me with additional information.

The versioning that is shown in the subsonic log in the web interface is part of Subsonic's internal logging and versioning. That has limited bearing on the version of the snap that is installed on your server.

Based on your feedback I have set up a testing environment in which I should catch this and similar issues before publishing to stable.

At the moment I am building a new set of snap packages that bring the environment up to core18 based on Ubuntu 18.04. (I know 20.04 is out, but core20 is not yet available).

Would you be willing to try the new candidate version when it becomes available?

**Comment by arubislander** [comment]
The new snap is available in the release/candidate channel (6.1.6+snap13)

**Comment by desroches25** [comment]
Happy to help. I have the candidate release running. I've recently switched across to 20.04 in an attempt to remediate this issue. 

tracking:     latest/candidate
refresh-date: today at 11:06 UTC
channels:
  latest/stable:    6.1.6+snap10 2020-05-12 (180) 161MB -
  latest/candidate: 6.1.6+snap13 2020-05-13 (200) 173MB -

**Comment by arubislander** [comment]
The snap package is self contained, so it should not matter what version of the OS you are running.
I see you are now on the 6.1.6+snap13 version of the snap package. Does it still work as it should? If it does I will promote it to stable.

**Comment by desroches25** [comment]
Yes, can confirm that it is working correctly

**Comment by arubislander** [comment]
Based on your confirmation I have promoted the snap in the candidate channel to stable. I have also closed the candidate channel, so your install will be automatically promoted to tracking stable.

Thank you again for your help! I hope you will continue enjoying Subsonic server. Spread the word!
